### PR TITLE
Hotfix/automation custom script.sh

### LINKED ISSUE #24: Bug in Automation_Custom_Script.sh
After installing the system, ` tail -f /var/tmp/dietpi/logs/dietpi-firstrun-setup.log`  show:
```
[  OK  ] DietPi-Services | restart : cron
[  OK  ] DietPi-Services | restart : telegraf
[ INFO ] DietPi-Services | skip : sailtrack-status (disabled)
[ INFO ] DietPi-Services | skip : sailtrack-timesync (disabled)
[ INFO ] DietPi-Services | skip : sailtrack-tileserver (disabled)
[ INFO ] DietPi-Services | skip : sailtrack-processor (disabled)
[ INFO ] DietPi-Software | Starting installed services not controlled by DietPi-Services
[  OK  ] DietPi-Software | systemctl start hostapd
[  OK  ] DietPi-Software | systemctl start isc-dhcp-server
```
And the dashboard is not displayed correctly and by checking the journalctl we see:
```
Nov 05 16:52:58 sailtrack-core systemd[1]: Starting Telegraf...
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Loading config: /etc/telegraf/telegraf.conf
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Loading config: /etc/telegraf/telegraf.d/sailtrack-telegraf.conf
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Starting Telegraf 1.28.3 brought to you by InfluxData the makers of InfluxDB
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Loaded inputs: cpu disk diskio kernel mem mqtt_consumer (2x) processes swap system
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Loaded aggregators:
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Loaded processors:
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Loaded secretstores:
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Loaded outputs: influxdb websocket
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! Tags enabled: host=sailtrack-core
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"sailtrack-core", Flush Interval:10s
Nov 05 16:52:59 sailtrack-core systemd[1]: Started Telegraf.
Nov 05 16:52:59 sailtrack-core influxd-systemd-start.sh[5182]: ts=2023-11-05T15:52:59.137298Z lvl=info msg="Executing query" log_id=0lK1BWZ0000 service=query query="CREATE DATABASE \"sailtrack-data\""
Nov 05 16:52:59 sailtrack-core influxd-systemd-start.sh[5182]: [httpd] ::1 - admin [05/Nov/2023:16:52:59 +0100] "POST /query HTTP/1.1 {'q': 'CREATE DATABASE "sailtrack-data"'}" 200 57 "-" "Telegraf/1.28.3 Go/1.21.3" 64ac87aa-7bf3-11ee-8062-b827ebad2359 1603
Nov 05 16:52:59 sailtrack-core grafana[5231]: logger=authn.service t=2023-11-05T16:52:59.141326694+01:00 level=info msg="Failed to authenticate request" client=auth.client.api-key error="[api-key.invalid] API key is invalid"
Nov 05 16:52:59 sailtrack-core grafana[5231]: logger=context userId=0 orgId=0 uname= t=2023-11-05T16:52:59.141753725+01:00 level=info msg="Request Completed" method=GET path=/api/live/push/sailtrack-data status=403 remote_addr=[::1] time_ms=0 duration=579.583µs size=32 referer= handler=/api/live/push/:streamId
Nov 05 16:52:59 sailtrack-core telegraf[6367]: 2023-11-05T15:52:59Z E! [agent] Failed to connect to [outputs.websocket], retrying in 15s, error was "error dial: websocket: bad handshake"
Nov 05 16:53:14 sailtrack-core grafana[5231]: logger=authn.service t=2023-11-05T16:53:14.146443302+01:00 level=info msg="Failed to authenticate request" client=auth.client.api-key error="[api-key.invalid] API key is invalid"
Nov 05 16:53:14 sailtrack-core grafana[5231]: logger=context userId=0 orgId=0 uname= t=2023-11-05T16:53:14.146811532+01:00 level=info msg="Request Completed" method=GET path=/api/live/push/sailtrack-data status=403 remote_addr=[::1] time_ms=0 duration=544.791µs size=32 referer= handler=/api/live/push/:streamId
Nov 05 16:53:14 sailtrack-core telegraf[6367]: 2023-11-05T15:53:14Z E! [telegraf] Error running agent: connecting output outputs.websocket: error connecting to output "outputs.websocket": error dial: websocket: bad handshake
Nov 05 16:53:14 sailtrack-core systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 16:53:14 sailtrack-core systemd[1]: telegraf.service: Failed with result 'exit-code'.
Nov 05 16:53:14 sailtrack-core systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 111.
Nov 05 16:53:14 sailtrack-core systemd[1]: Stopped Telegraf.
```

So the problem seems to be that telgraf can't communicate properly with grafana because the service did not start properly..
Through further analysis I seem to have noticed that the problem may be related to `Automation_Custom_Script.sh`
Specifically at the end of` /var/tmp/dietpi/logs/dietpi-automation_custom_script.log`
it shows:
```
[FAILED] /boot/dietpi/dietpi-services dietpi_controlled telegraf
[FAILED] Unable to continue, command will now terminate.
```

### PR DESCRIPTION
**Pull request by Magform**
Fix for [Issue 24](https://github.com/metis-vela-unipd/sailtrack-core/issues/24)

Before merging, I recommend testing the changes on the real system to ensure everything works as expected.

### CODE REVIEW

File: Automation_Custom_Script.sh [hunk 1]
```diff
@@ -18,11 +18,16 @@ G_CONFIG_INJECT "+ sailtrack-status" "+ sailtrack-status" /boot/dietpi/.dietpi-s
 G_CONFIG_INJECT "+ sailtrack-timesync" "+ sailtrack-timesync" /boot/dietpi/.dietpi-services_include_exclude
 G_CONFIG_INJECT "+ sailtrack-tileserver" "+ sailtrack-tileserver" /boot/dietpi/.dietpi-services_include_exclude
 G_CONFIG_INJECT "+ sailtrack-processor" "+ sailtrack-processor" /boot/dietpi/.dietpi-services_include_exclude
-G_EXEC /boot/dietpi/dietpi-services dietpi_controlled telegraf
-G_EXEC /boot/dietpi/dietpi-services dietpi_controlled sailtrack-status
-G_EXEC /boot/dietpi/dietpi-services dietpi_controlled sailtrack-timesync
-G_EXEC /boot/dietpi/dietpi-services dietpi_controlled sailtrack-tileserver
-G_EXEC /boot/dietpi/dietpi-services dietpi_controlled sailtrack-processor
+G_EXEC /boot/dietpi/dietpi-services enable telegraf
+G_EXEC /boot/dietpi/dietpi-services start telegraf
```
Comment (matteocarnelos) [inline Automation_Custom_Script.sh]: Enabling and starting Telegraf is unnecessary in this context since it's just finished the installation process and therefore it's already enabled. Consider removing these lines:
```suggestion
```

File: Automation_Custom_Script.sh [hunk 2]
```diff
@@ -18,11 +18,16 @@ G_CONFIG_INJECT "+ sailtrack-status" "+ sailtrack-status" /boot/dietpi/.dietpi-s
...
+G_EXEC /boot/dietpi/dietpi-services enable sailtrack-status
+G_EXEC /boot/dietpi/dietpi-services start sailtrack-status
+G_EXEC /boot/dietpi/dietpi-services enable sailtrack-timesync
+G_EXEC /boot/dietpi/dietpi-services start sailtrack-timesync
+G_EXEC /boot/dietpi/dietpi-services enable sailtrack-tileserver
+G_EXEC /boot/dietpi/dietpi-services start sailtrack-tileserver
+G_EXEC /boot/dietpi/dietpi-services enable sailtrack-processor
+G_EXEC /boot/dietpi/dietpi-services start sailtrack-processor
```
Comment (matteocarnelos) [inline Automation_Custom_Script.sh]: I wouldn't start the SailTrack services immediately. At this point the setup is still in an unfinished state. The setup finishes with a restart, which will start them if they are enabled. Therefore, it makes more sense to just enable the services here and let them start at the next boot, when the setup is completed. Consider removing the start of the services:
```suggestion
G_EXEC /boot/dietpi/dietpi-services enable sailtrack-status
G_EXEC /boot/dietpi/dietpi-services enable sailtrack-timesync
G_EXEC /boot/dietpi/dietpi-services enable sailtrack-tileserver
G_EXEC /boot/dietpi/dietpi-services enable sailtrack-processor
```

File: Automation_Custom_Script.sh [hunk 3]
```diff
@@ -34,8 +39,12 @@ done
 # Configure passwords and keys
 G_EXEC /boot/dietpi/dietpi-services restart grafana-server
 GLOBAL_PASSWORD=$(openssl enc -d -a -md sha256 -aes-256-cbc -iter 10000 -salt -pass pass:'DietPiRocks!' -in /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin)
+SERVICE_ACCOUNT_ID=$(\
+  curl --retry 10 --retry-delay 5 --retry-connrefused -s -X POST -H "Content-Type: application/json" -d '{"name":"telegraf", "role": "Admin"}' "http://admin:$GLOBAL_PASSWORD@localhost:3001/api/serviceaccounts" | \
```
Comment (matteocarnelos) [inline Automation_Custom_Script.sh]: I would personally prefer to have a single "SailTrack" service account with multiple tokens, one for each component (e.g. Telegraf). Therefore, I'd suggest to rename the service account:
```suggestion
  curl --retry 10 --retry-delay 5 --retry-connrefused -s -X POST -H "Content-Type: application/json" -d '{"name":"SailTrack", "role": "Admin"}' "http://admin:$GLOBAL_PASSWORD@localhost:3001/api/serviceaccounts" | \
```

File: Automation_Custom_Script.sh [hunk 4]
```diff
@@ -34,8 +39,12 @@ done
 # Configure passwords and keys
 G_EXEC /boot/dietpi/dietpi-services restart grafana-server
 GLOBAL_PASSWORD=$(openssl enc -d -a -md sha256 -aes-256-cbc -iter 10000 -salt -pass pass:'DietPiRocks!' -in /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin)
+SERVICE_ACCOUNT_ID=$(\
```
Comment (matteocarnelos) [inline Automation_Custom_Script.sh]: Similarly to the api key variable, I'd suggest to prefix this variable with `GRAFANA_`:
```suggestion
GRAFANA_SERVICE_ACCOUNT_ID=$(\
```

File: Automation_Custom_Script.sh [hunk 5]
```diff
@@ -34,8 +39,12 @@ done
...
+  curl --retry 10 --retry-delay 5 --retry-connrefused -s -X POST -H "Content-Type: application/json" -d '{"name":"telegraf", "role": "Admin"}' "http://admin:$GLOBAL_PASSWORD@localhost:3001/api/serviceaccounts" | \
+  python3 -c "import sys, json; print(json.load(sys.stdin)['id'])" \
+)
 GRAFANA_API_KEY=$(\
-  curl --retry 10 --retry-delay 5 --retry-connrefused -s -X POST -H "Content-Type: application/json" -d '{"name":"sailtrack", "role": "Admin"}' "http://admin:$GLOBAL_PASSWORD@localhost:3001/api/auth/keys" | \
+  curl --retry 10 --retry-delay 5 --retry-connrefused -s -X POST -H "Content-Type: application/json" -d '{"name":"telegraf-token"}' "http://admin:$GLOBAL_PASSWORD@localhost:3001/api/serviceaccounts/$SERVICE_ACCOUNT_ID/tokens" | \
```
Comment (matteocarnelos) [inline Automation_Custom_Script.sh]: Based on my previous comment, this can simply become "Telegraf":
```suggestion
  curl --retry 10 --retry-delay 5 --retry-connrefused -s -X POST -H "Content-Type: application/json" -d '{"name":"Telegraf"}' "http://admin:$GLOBAL_PASSWORD@localhost:3001/api/serviceaccounts/$SERVICE_ACCOUNT_ID/tokens" | \
```

**Review by matteocarnelos — CHANGES_REQUESTED** [review]
I _finally_ had time to test and review the changes suggested in this PR.

Thanks for the fix! However, following some testing, the automation script needs some more fixes. For example, Grafana deprecated the `grafana-cli` utility that we are using.
I'll follow with a new PR after this one with these fixes and update `sailtrack-ground` accordingly.

For this PR, overall it's great! I just highlighted some nits.

**Review by matteocarnelos — APPROVED** [review]
LGTM
